"""Markdown report generation for SearchEval Lab."""

from __future__ import annotations

from pathlib import Path

from searcheval.benchmarks.runner import BenchmarkRun, benchmark_summary
from searcheval.eval.failure_analysis import find_weak_queries


def format_metric_value(value: object) -> str:
    """Format a metric value for a Markdown report."""
    if isinstance(value, float):
        return f"{value:.4f}"

    return str(value)


def render_summary_table(run: BenchmarkRun) -> str:
    """Render the aggregate benchmark summary as a Markdown table."""
    summary = benchmark_summary(run)

    lines = [
        "| Metric | Value |",
        "|---|---:|",
    ]

    for metric_name, value in summary.items():
        lines.append(f"| {metric_name} | {format_metric_value(value)} |")

    return "\n".join(lines)


def render_per_query_table(run: BenchmarkRun) -> str:
    """Render per-query evaluation metrics as a Markdown table."""
    metric_names = list(run.evaluation.aggregate_metrics.keys())

    header = ["Query ID", *metric_names, "Retrieved Docs", "Relevant Docs"]
    separator = ["---", *["---:" for _ in metric_names], "---", "---"]

    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(separator) + " |",
    ]

    for query_evaluation in run.evaluation.per_query:
        metric_values = [
            format_metric_value(query_evaluation.metrics[metric_name])
            for metric_name in metric_names
        ]

        retrieved_docs = ", ".join(query_evaluation.retrieved_doc_ids)
        relevant_docs = ", ".join(query_evaluation.relevant_doc_ids)

        row = [
            query_evaluation.query_id,
            *metric_values,
            retrieved_docs,
            relevant_docs,
        ]

        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines)


def render_weak_query_table(
    run: BenchmarkRun,
    metric_name: str | None = None,
    limit: int = 5,
) -> str:
    """Render the weakest queries for a selected metric."""
    if metric_name is None:
        metric_name = f"ndcg_at_{run.k}"

    weak_queries = find_weak_queries(
        report=run.evaluation,
        metric_name=metric_name,
        limit=limit,
    )

    lines = [
        "| Query ID | Metric | Score | Retrieved Docs | Relevant Docs |",
        "|---|---|---:|---|---|",
    ]

    for weak_query in weak_queries:
        retrieved_docs = ", ".join(weak_query.retrieved_doc_ids)
        relevant_docs = ", ".join(weak_query.relevant_doc_ids)

        row = [
            weak_query.query_id,
            weak_query.metric_name,
            format_metric_value(weak_query.score),
            retrieved_docs,
            relevant_docs,
        ]

        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines)


def render_latency_table(run: BenchmarkRun) -> str:
    """Render per-query latency measurements as a Markdown table."""
    lines = [
        "| Query ID | Latency ms |",
        "|---|---:|",
    ]

    for latency in run.query_latencies:
        lines.append(f"| {latency.query_id} | {latency.latency_ms:.4f} |")

    return "\n".join(lines)


def render_markdown_report(
    run: BenchmarkRun,
    run_id: str | None = None,
) -> str:
    """Render a full benchmark report in Markdown."""
    title = "# SearchEval Lab Benchmark Report"

    if run_id:
        run_identity = f"**Run ID:** `{run_id}`"
    else:
        run_identity = "**Run ID:** not provided"

    weak_query_metric = f"ndcg_at_{run.k}"

    sections = [
        title,
        "",
        "## Run Summary",
        "",
        run_identity,
        "",
        f"**Engine:** `{run.engine_name}`",
        "",
        f"**Top-K:** `{run.k}`",
        "",
        "## Aggregate Metrics",
        "",
        render_summary_table(run),
        "",
        "## Per-Query Metrics",
        "",
        render_per_query_table(run),
        "",
        "## Weak Query Analysis",
        "",
        f"Weakest queries ranked by `{weak_query_metric}`.",
        "",
        render_weak_query_table(
            run=run,
            metric_name=weak_query_metric,
            limit=5,
        ),
        "",
        "## Query Latency",
        "",
        render_latency_table(run),
        "",
        "## Notes",
        "",
        "This report was generated by SearchEval Lab.",
        "",
        "The benchmark evaluates search quality using ranking metrics such as "
        "Precision@K, Recall@K, MRR@K, and NDCG@K.",
        "",
    ]

    return "\n".join(sections)


def save_markdown_report(
    run: BenchmarkRun,
    output_path: Path,
    run_id: str | None = None,
) -> Path:
    """Save a benchmark report as a Markdown file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    report = render_markdown_report(
        run=run,
        run_id=run_id,
    )

    output_path.write_text(report, encoding="utf-8")

    return output_path
